services:
  - type: web
    name: product-cost-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Set this in Render dashboard
      - key: SECRET_KEY
        sync: false  # Set this in Render dashboard
